### PR TITLE
Add Goals 

### PR DESCRIPTION
**Pull request by athul**
Please checkout to this branch and make the required changes. All changes will be reviewed

### CODE REVIEW

**Review by jagannathBhat — CHANGES_REQUESTED** [review]
I was hoping we could come up with something more specific. Like,

# Problems
1. Participants don't have a list of hackathons happening in Kerala.
2. Hackathon dates colliding with each other and exams is a problem for participants.
3. Participants don't have a way to know if the hackathon is worth their time.
4. Participants with little or no experience can't find mentors to help them out.

# Outcomes
1. Interested people are aware of all hackathons happening in Kerala.
2. Organizers can find the right dates to organize their hackathons on.
3. People can decide if a hackathon is worth attending based on feedback from previous iterations of the hackathon.
4. People interested in mentoring can inform they are available and participants in need of mentors can approach these people.

# Solution
1. A list of hackathons happening in Kerala.
2. A calendat showing upcoming hackathons, exams and other important events.
3. IMDB for hackathons. Participants rate and comment on hackathons and organizers.
4. List of mentors available for all hackathons and their contacts.

**Comment by athul** [comment]
@jagannathBhat Could you Update the file and do the required. ❤️

**Comment by jagannathBhat** [comment]
I have created a [pull request](https://github.com/hhkerala/discuss/pull/6) to the [goals](https://github.com/hhkerala/discuss/tree/goals) branch with the changes I mentioned before.

**Comment by athul** [comment]
Okay, Will check it out and do the req

**Pull request merged**
